# Generated by Django 3.2 on 2022-09-29 17:54

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='Offer', variations={'thumb': {'crop': True, 'height': 681, 'width': 423}}, verbose_name='Imagem')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Atributo', 'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='01. Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='02. Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 557, 'width': 460}}, verbose_name='03. Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='04. Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='Product', variations={'thumb': {'crop': True, 'height': 597, 'width': 460}}, verbose_name='05. Imagem'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
